### ISSUE TITLE
Pas de mise à jour des mots automatique

### ISSUE THREAD

**Issue by madtibo** [YunoHost-Apps/sutom_ynh#12]
### Describe the bug

Lors de l'installation, un mot est disponible le premier jour. Les jours suivants, il n'y a pas de mots disponibles :

![Capture d’écran du 2023-01-29 21-03-04](https://user-images.githubusercontent.com/19191236/215352812-049dd241-62be-4640-b1b4-52007a2a976d.png)

Le fichier cron.sh semble mettre à jour ce mot mais je ne trouve pas de trace de la tâche l'exécutant.

Dispo pour tester des trucs !

### Context

Installation classique de l'app par l'admin.

**Comment by ghost** [comment]
Bonjour,

Problème identique, le mot reste le même.

en lançant le cron.sh, j'obtiens un message d'erreur :

```
/var/www/sutom/utils/majATrouver.js:17
  var dictionnaire = contenu.split("\n");
                             ^

TypeError: Cannot read properties of undefined (reading 'split')
    at ReadFileContext.callback (/var/www/sutom/utils/majATrouver.js:17:30)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:319:13)
./cron.sh: line 5: tsc: command not found

```

**Comment by isAAAc** [comment]
same here

**Comment by isAAAc** [comment]
@ericgaspar , do you have a quickfix handy?
looks like the split function isn't recognised anymore ?

**Comment by Tagadda** [comment]
This fails because the file `data/motsAtrouve.txt` doesn't exist.
https://framagit.org/JonathanMM/sutom/-/blob/main/utils/majATrouver.js#L15

**Comment by isAAAc** [comment]
file exists since yesterday 
```
root@krashboyz:~# ls -al /var/www/sutom/data/motsATrouve.txt 
-rw-rw-r-- 1 sutom sutom 0 Sep 25 19:04 /var/www/sutom/data/motsATrouve.txt
```
`cron.sh` changed like this:
```
root@krashboyz:/var/www/sutom# cat cron.sh 
#!/bin/bash

#npm ci
#node utils/majATrouver.js
#tsc


PATH=/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin npm ci
PATH=/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin node utils/majATrouver.js
PATH=/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin npm exec -- tsc
```
the cron is running but no change on the app, "no word find for today"
```
root@krashboyz:/var/www/sutom# sudo -u sutom ./cron.sh 

added 139 packages, and audited 140 packages in 4s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
root@krashboyz:/var/www/sutom# sudo -u sutom ./cron.sh 

added 139 packages, and audited 140 packages in 3s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
i tried : `sudo -u sutom PATH=/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin npm fund` but it doesn't work fund looks like a bad command for npm :/ 

and i don't know if it is related to the no-renew of the word of the day

https://docs.npmjs.com/cli/v6/commands/npm-fund tells package name is needed for argument

edit: 
```
root@krashboyz:/var/www/sutom# sudo -u sutom PATH=/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin npm config ls -l
; cli configs
long = true
user-agent = "npm/3.10.10 node/v20.7.0 linux x64"

; default values
access = null
also = null
always-auth = false
bin-links = true
browser = null
ca = null
cache = "/var/www/sutom/.npm"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
depth = null
description = true
dev = false
dry-run = false
editor = "vi"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "/opt/node_n/n/versions/node/20.7.0/etc/npmrc"
globalignorefile = "/opt/node_n/n/versions/node/20.7.0/etc/npmignore"
group = 0
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "/var/www/sutom/.npm-init.js"
init-version = "1.0.0"
json = false
key = null
legacy-bundling = false
link = false
local-address = undefined
loglevel = "warn"
; long = false (overridden)
maxsockets = 50
message = "%s"
node-version = "20.7.0"
npat = false
onload-script = null
only = null
optional = true
parseable = false
prefix = "/opt/node_n/n/versions/node/20.7.0"
production = false
progress = true
proprietary-attribs = true
proxy = null
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
rollback = true
save = false
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
scope = ""
searchexclude = null
searchopts = ""
searchsort = "name"
shell = "/usr/sbin/nologin"
shrinkwrap = true
sign-git-tag = false
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
tmp = "/tmp"
umask = 18
unicode = true
unsafe-perm = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "/var/www/sutom/.npmrc"
version = false
versions = false
viewer = "man"
```
there is no `/var/www/sutom/.npmrc`

what does mean 
```
14 packages are looking for funding
  run `npm fund` for details
 ```
 searching on

**Comment by orhtej2** [comment]
Given my non-existent French speaking capabilities have you considered running https://framagit.org/JonathanMM/sutom/-/blob/main/utils/genererMotTrouve.js ? I think this util is meant to seed input for `motsATrouve.js`

```sh
cd /var/www/sutom
sudo -u sutom PATH=/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin npm run utils/genererMotTrouve.js
```

**Comment by isAAAc** [comment]
issue opened sutom size: https://framagit.org/JonathanMM/sutom/-/issues/71

**Comment by isAAAc** [comment]
> Given my non-existent French speaking capabilities have you considered running https://framagit.org/JonathanMM/sutom/-/blob/main/utils/genererMotTrouve.js ? I think this util is meant to seed input for `motsATrouve.js`
> 
> ```shell
> cd /var/www/sutom
> sudo -u sutom PATH=/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin npm run utils/genererMotTrouve.js
> ```

yup, there is a syntaxe error: 
```
root@krashboyz:/var/www/sutom# sudo -u sutom PATH=/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin node utils/genererMotTrouve.js 
/var/www/sutom/utils/genererMotTrouve.js:20
        let motAnalyse = mot.normalize("NFD").replace(/\p{Diacritic}/gu, "");
                                             ^

SyntaxError: Invalid regular expression: /\p{Diacritic}/: Invalid escape
    at /var/www/sutom/utils/genererMotTrouve.js:20:46
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)



root@krashboyz:/var/www/sutom# sudo -u sutom PATH=/opt/node_n/n/versions/node/20/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin node utils/majATrouver.js
/var/www/sutom/utils/majATrouver.js:24
        .replace(/\p{Diacritic}/gu, "")
        ^

SyntaxError: Invalid regular expression: /\p{Diacritic}/: Invalid escape
    at motsFiges.map (/var/www/sutom/utils/majATrouver.js:24:9)
    at Array.map (native)
    at /var/www/sutom/utils/majATrouver.js:21:6
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
    ``` 
    :/

**Comment by isAAAc** [comment]
upgraded to version 2023.06.13~ynh1 thuesday, 

i can see in the install logs: `ln -sf /var/www/sutom/public/js/mots/listeMotsProposables.js /var/www/sutom/public/js/mots/listeMotsProposables.9.D.js`   and those files are populated, 

but still no word the second day :/

tell me if/how i can help ;)

**Comment by rockflo** [comment]
Same for me. No word the second day.
In the console of the browser I can see that it is looking for files at...

...mydomain.../fonts/Roboto-Regular.ttf
...mydomain.../ts/main.ts

... instead of looking for them at:

...mydomain.../sutom/fonts/Roboto-Regular.ttf
...mydomain.../sutom/ts/main.ts
